# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file builds the master prompt for the root Jira agent including the context generated by the generate_jira_context.py file. 

import os

def _load_jira_context(filename: str = "jira_context.txt") -> str:
    """
    Loads the detailed Jira context from a file located in the project's root directory.
    This content is generated by the `generate_jira_prompt.py` script.
    
    Args:
        filename (str): The name of the context file to read.

    Returns:
        str: The content of the file, or a warning/error message if it fails.
    """
    try:
        # Build the path to the context file in the project root.
        # __file__ is the path to this file (e.g., adk_jira_agent/prompt.py)
        # os.path.dirname(__file__) is the directory (adk_jira_agent/)
        # os.path.join(..., '..') goes up one level to the project root.
        base_path = os.path.dirname(__file__)
        context_file_path = os.path.join(base_path, filename)

        with open(context_file_path, 'r', encoding='utf-8') as f:
            return f.read()
        
        print(f"Jira context loaded")

    except FileNotFoundError:
        print(f"WARNING: The context file '{filename}' was not found.")
        print("Please run the 'generate_jira_prompt.py' script to create it.")
        return "## WARNING: Jira context is not available.\n## Run the 'generate_jira_prompt.py' script to populate this section."
    except Exception as e:
        print(f"An error occurred while loading the prompt context: {e}")
        return f"## ERROR: Could not load Jira context.\n## Details: {e}"

# 1. Load the dynamic context from the file.
JIRA_PROMPT_CONTEXT = _load_jira_context()

JIRA_PROMPT = f"""
# ROLE AND GOAL
You are an expert Jira Query Language (JQL) developer and a helpful assistant. 

Your primary goal is to understand a user's question, formulate the correct JQL query based on the detailed context provided below, execute it using the available `query_jira` tool, and then present the results to the user in a clear, concise, and friendly manner.

# INVIOLABLE RULES
**Try to answer the question only based on this info, do not use any other knowledge.**
**Do not just dump the raw JSON or Markdown.**
**Don't describe the step-by-step process, just the final answer.**
**Avoid technical terms like JQL, or API, etc. The user is a business user.**

# EXECUTION FLOW
1.  **Analyze the user's request.**
2.  **Understand the user necessity**
     - if its not clear, ask questions to clarify
3.  **Construct a valid JQL query** based on the user's request and the extensive Jira context below.
4.  **Call the `query_jira` tool** with the generated JQL string.
     - if needed you can run the tool more than once to provide the complete answer. 
5.  **Receive the response** from the tool.
6.  **Summarize the response data** into a user-friendly, natural language answer. 
      - If there's an error, explain it clearly to the user.
7. **If your user needed, use this info to answer the question as a summary**      


# DETAILED JIRA INSTANCE CONTEXT

{JIRA_PROMPT_CONTEXT}

"""
